### ISSUE TITLE
Behaviour with Supports and other ABCs

### ISSUE THREAD

**Issue by demianw** [ilevkivskyi/typing_inspect#42]
Hello,

is this
```
import typing
import typing_inspect
typing_inspect.is_generic_type(typing.SupportsInt) is True

```
supposed to happen?
Thanks

**Comment by ilevkivskyi** [comment]
Yes, this is kind of intentional. The function doesn't answer whether a type can be further parameterised, but whether it has `Generic` somewhere in MRO. For example `is_generic_type(List[int])` is also `True`.

If you want to check whether a type can be further parameterised use `get_parameters()`.
